//! The supported disc build, as a per-file CRC32 manifest.
//!
//! Every byte offset baked into the port (WAD catalog offsets, fire tables,
//! sprite descriptors) assumes one specific pressing of the CD. A different
//! pressing or a corrupted rip does not fail cleanly: it produces garbage
//! reads or a panic deep inside a decoder, with no hint that the input was
//! wrong. [`verify`] turns that into an upfront, per-file report.
//!
//! The table is generated, not hand-typed: run the `generate_manifest`
//! example against a known-good image and paste its output here.

use thiserror::Error;

use crate::AssetSource;
use crate::error::{DiscError, Result};

/// One file of the supported data track.
#[derive(Debug, Clone, Copy)]
pub struct ManifestEntry {
    /// Canonical name, e.g. `"LEVEL_1.WAD"` or `"FLI/INTRO.FLI"`.
    pub name: &'static str,
    pub size: u32,
    pub crc32: u32,
}

/// How a file deviates from the manifest.
#[derive(Debug, Clone, Copy, Error)]
pub enum Mismatch {
    #[error("{name}: missing from the data track")]
    Missing { name: &'static str },
    #[error("{name}: size {actual} (expected {expected})")]
    Size {
        name: &'static str,
        expected: u32,
        actual: u32,
    },
    #[error("{name}: crc32 {actual:08x} (expected {expected:08x})")]
    Crc32 {
        name: &'static str,
        expected: u32,
        actual: u32,
    },
}

/// Check every manifest entry against the source, collecting all deviations.
///
/// An empty result means the image matches the supported build. Read errors
/// other than a missing file (a truncated bin, I/O failure) propagate as
/// `Err`.
pub fn verify(source: &dyn AssetSource) -> Result<Vec<Mismatch>> {
    let mut mismatches = Vec::new();

    for entry in MANIFEST {
        let bytes = match source.read(entry.name) {
            Ok(bytes) => bytes,
            Err(DiscError::FileNotFound(_)) => {
                mismatches.push(Mismatch::Missing { name: entry.name });
                continue;
            }
            Err(error) => return Err(error),
        };

        if bytes.len() != entry.size as usize {
            mismatches.push(Mismatch::Size {
                name: entry.name,
                expected: entry.size,
                actual: bytes.len() as u32,
            });
            continue;
        }

        let actual = crc32fast::hash(&bytes);

        if actual != entry.crc32 {
            mismatches.push(Mismatch::Crc32 {
                name: entry.name,
                expected: entry.crc32,
                actual,
            });
        }
    }

    Ok(mismatches)
}

/// Every file of the supported data track. Generated by the
/// `generate_manifest` example; do not edit by hand.
#[rustfmt::skip]
pub const MANIFEST: &[ManifestEntry] = &[
    ManifestEntry { name: "ALIENBG.SP1", size: 25600, crc32: 0x8bf6f094 },
    ManifestEntry { name: "ALIENBG.SP2", size: 25600, crc32: 0x45a00f34 },
    ManifestEntry { name: "ALIENBG.SP3", size: 25600, crc32: 0xbd29c641 },
    ManifestEntry { name: "ALIENBG.SP4", size: 25600, crc32: 0x51c59050 },
    ManifestEntry { name: "BACK3.RAW", size: 64000, crc32: 0x50bffdea },
    ManifestEntry { name: "BALKEN.RAW", size: 1024, crc32: 0x9f83f003 },
    ManifestEntry { name: "BURNING.SMP", size: 4368, crc32: 0x6b86caab },
    ManifestEntry { name: "BURNING2.SMP", size: 5450, crc32: 0x03388cad },
    ManifestEntry { name: "CANYON.SP1", size: 25600, crc32: 0x85a0697f },
    ManifestEntry { name: "CANYON.SP2", size: 25600, crc32: 0xf41ee804 },
    ManifestEntry { name: "CANYON.SP3", size: 25600, crc32: 0x37133bc1 },
    ManifestEntry { name: "CANYON.SP4", size: 25600, crc32: 0x8c0794e4 },
    ManifestEntry { name: "CHAINGUN.SMP", size: 6632, crc32: 0xf1996de2 },
    ManifestEntry { name: "CHAINHIT.SMP", size: 582, crc32: 0x72877bad },
    ManifestEntry { name: "CHANGEWE.SMP", size: 11460, crc32: 0x9fd39cea },
    ManifestEntry { name: "COVER3.BDY", size: 70494, crc32: 0x0c699c58 },
    ManifestEntry { name: "COVER3.PAL", size: 768, crc32: 0xaabc3302 },
    ManifestEntry { name: "EXPLOGEG.SMP", size: 7002, crc32: 0x8faca695 },
    ManifestEntry { name: "EXPLOSIO.SMP", size: 16188, crc32: 0x0b1b63d6 },
    ManifestEntry { name: "EXPLOSTO.SMP", size: 6408, crc32: 0x1f1c92e2 },
    ManifestEntry { name: "EXTRAABG.SMP", size: 1980, crc32: 0xb8ceefac },
    ManifestEntry { name: "EXTRAERS.SMP", size: 9078, crc32: 0x3470aa34 },
    ManifestEntry { name: "EXTRAGEN.SMP", size: 3352, crc32: 0xcdcd684e },
    ManifestEntry { name: "EXTRAS.RAW", size: 53760, crc32: 0x1019e2b6 },
    ManifestEntry { name: "FLI/CANYON.FLI", size: 6331270, crc32: 0xcc0a2bff },
    ManifestEntry { name: "FLI/CREDZ.FLI", size: 556126, crc32: 0x9a93b976 },
    ManifestEntry { name: "FLI/FLY.FLI", size: 2306256, crc32: 0x59a88a8f },
    ManifestEntry { name: "FLI/GO2.FLI", size: 1197412, crc32: 0x36c6d4d3 },
    ManifestEntry { name: "FLI/HIGHSCOR.FLI", size: 334270, crc32: 0x243b2ec0 },
    ManifestEntry { name: "FLI/INTRO.FLI", size: 386376, crc32: 0x6ab41f71 },
    ManifestEntry { name: "FLI/LAVA.FLI", size: 6722930, crc32: 0xbdd5ce0a },
    ManifestEntry { name: "FLI/SPACE1.FLI", size: 418024, crc32: 0x3e0123a0 },
    ManifestEntry { name: "FLI/SPACE2.FLI", size: 2813794, crc32: 0xdf4af2c4 },
    ManifestEntry { name: "FLI/SPACE3.FLI", size: 369138, crc32: 0x76e04cfc },
    ManifestEntry { name: "FLI/TEND.FLI", size: 2724490, crc32: 0x778f4e66 },
    ManifestEntry { name: "FLI/WALDENDE.FLI", size: 577406, crc32: 0xaf6ee6c5 },
    ManifestEntry { name: "FONT.RAW", size: 19840, crc32: 0x05b6d78c },
    ManifestEntry { name: "FONT2.RAW", size: 19840, crc32: 0xe69c31c6 },
    ManifestEntry { name: "GEGROCKE.SMP", size: 11818, crc32: 0x2591b0c6 },
    ManifestEntry { name: "GEGSHOT.SMP", size: 1980, crc32: 0x61ff789f },
    ManifestEntry { name: "GUNS.RAW", size: 3840, crc32: 0xbd943a9b },
    ManifestEntry { name: "HIGH.TXT", size: 176, crc32: 0xf046b1ef },
    ManifestEntry { name: "INSTALL.EXE", size: 47752, crc32: 0x48346589 },
    ManifestEntry { name: "KANONE.SMP", size: 8030, crc32: 0x7fa5d4a5 },
    ManifestEntry { name: "LAVA.BIN", size: 2025074, crc32: 0x295863c7 },
    ManifestEntry { name: "LAVAH.SP1", size: 25600, crc32: 0x87b81d03 },
    ManifestEntry { name: "LAVAH.SP2", size: 25600, crc32: 0xd0bebfd6 },
    ManifestEntry { name: "LAVAH.SP3", size: 25600, crc32: 0x6069555e },
    ManifestEntry { name: "LAVAH.SP4", size: 25600, crc32: 0x13e36fa3 },
    ManifestEntry { name: "LEVEL_1.WAD", size: 75472, crc32: 0x917a536f },
    ManifestEntry { name: "LEVEL_2.WAD", size: 61328, crc32: 0x9bedeaef },
    ManifestEntry { name: "LEVEL_3.WAD", size: 89952, crc32: 0xc8586ca7 },
    ManifestEntry { name: "LEVEL_4.WAD", size: 61552, crc32: 0x766100b5 },
    ManifestEntry { name: "LEVEL_5.WAD", size: 81840, crc32: 0x87c24d1c },
    ManifestEntry { name: "LEVEL_6.WAD", size: 64112, crc32: 0x4802faab },
    ManifestEntry { name: "LEVEL_7.WAD", size: 92272, crc32: 0x8d1d5ae1 },
    ManifestEntry { name: "LGEGSHOT.SMP", size: 2880, crc32: 0x3b45de0b },
    ManifestEntry { name: "LIGHTS.RAW", size: 672, crc32: 0x57960ab8 },
    ManifestEntry { name: "MISSHIT.SMP", size: 4780, crc32: 0xeb92dff7 },
    ManifestEntry { name: "MISSILE.SMP", size: 7984, crc32: 0x6139a962 },
    ManifestEntry { name: "MULTISHO.SMP", size: 1742, crc32: 0xd3385bd6 },
    ManifestEntry { name: "NEO.BDY", size: 12706, crc32: 0xa696098f },
    ManifestEntry { name: "NEO.PAL", size: 768, crc32: 0x1ec6ef6b },
    ManifestEntry { name: "NUMBERS.RAW", size: 1080, crc32: 0xee6cd7ef },
    ManifestEntry { name: "OUT.BIN", size: 2045963, crc32: 0x4bb40322 },
    ManifestEntry { name: "PANEL.RAW", size: 10240, crc32: 0x89d09984 },
    ManifestEntry { name: "PLASMAGU.SMP", size: 6618, crc32: 0x3f6bff37 },
    ManifestEntry { name: "PTURN1.BN1", size: 44881, crc32: 0x103b1e7d },
    ManifestEntry { name: "PVESSEL.RAW", size: 64000, crc32: 0x9b3dc3c5 },
    ManifestEntry { name: "RACE1.BIN", size: 524255, crc32: 0x868ac39b },
    ManifestEntry { name: "RACEB2.SP1", size: 25600, crc32: 0x4b192387 },
    ManifestEntry { name: "RACEB2.SP2", size: 25600, crc32: 0x2d073b87 },
    ManifestEntry { name: "RACEB2.SP3", size: 25600, crc32: 0x17d25460 },
    ManifestEntry { name: "RACEB2.SP4", size: 25600, crc32: 0xa4cc32cd },
    ManifestEntry { name: "SCHEREN.SMP", size: 8516, crc32: 0xea79f81e },
    ManifestEntry { name: "SCORE.RAW", size: 2080, crc32: 0xa8f8ec0d },
    ManifestEntry { name: "SETUP.EXE", size: 42550, crc32: 0xf33ff9d3 },
    ManifestEntry { name: "SMART.RAW", size: 1440, crc32: 0x0050d82b },
    ManifestEntry { name: "START.EXE", size: 22064, crc32: 0xe60293df },
    ManifestEntry { name: "SURPLOGO.BDY", size: 6990, crc32: 0xa4ffe6e0 },
    ManifestEntry { name: "SURPLOGO.PAL", size: 768, crc32: 0x6222e277 },
    ManifestEntry { name: "TECHNO.BIN", size: 2532895, crc32: 0x16b4ab12 },
    ManifestEntry { name: "WALD.BIN", size: 2304324, crc32: 0x8506bb14 },
    ManifestEntry { name: "WALD.SP1", size: 25600, crc32: 0x774eacc9 },
    ManifestEntry { name: "WALD.SP2", size: 25600, crc32: 0x265d62a4 },
    ManifestEntry { name: "WALD.SP3", size: 25600, crc32: 0x5c1e075d },
    ManifestEntry { name: "WALD.SP4", size: 25600, crc32: 0x718ab5ac },
];
