name: release-please

on:
  push:
    branches: [main]

permissions: {}

jobs:
  release-please:
    name: release-please
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Generate GitHub token
        uses: actions/create-github-app-token@v3
        id: token
        with:
          client-id: ${{ secrets.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write
      - uses: googleapis/release-please-action@v5
        with:
          token: ${{ steps.token.outputs.token }}
